export interface NewsCategory {
  id: string;
  name: string;        // 한국어 카테고리명
  enName: string;      // 영어 카테고리명
  label?: string;      // 호환용 라벨 (한국어)
  enLabel?: string;    // 호환용 라벨 (영어)
  icon?: string;       // 카테고리 아이콘/이모지
}

export const NEWS_CATEGORIES: NewsCategory[] = [
  {
    id: "top-news",
    name: "주요뉴스",
    enName: "Top News",
    label: "주요뉴스",
    enLabel: "Top News",
    icon: "🔥",
  },
  {
    id: "mainnet",
    name: "메인넷",
    enName: "Mainnet",
    label: "메인넷",
    enLabel: "Mainnet",
    icon: "🌐",
  },
  {
    id: "node",
    name: "노드",
    enName: "Node",
    label: "노드",
    enLabel: "Node",
    icon: "💻",
  },
  {
    id: "mining",
    name: "채굴",
    enName: "Mining",
    label: "채굴",
    enLabel: "Mining",
    icon: "⛏️️",
  },
  {
    id: "wallet",
    name: "지갑",
    enName: "Wallet",
    label: "지갑",
    enLabel: "Wallet",
    icon: "👛",
  },
  {
    id: "community",
    name: "커뮤니티",
    enName: "Community",
    label: "커뮤니티",
    enLabel: "Community",
    icon: "👥",
  },
  {
    id: "commerce",
    name: "결제/커머스",
    enName: "Commerce",
    label: "결제/커머스",
    enLabel: "Commerce",
    icon: "🛒",
  },
  {
    id: "browser",
    name: "파이브라우저",
    enName: "Pi Browser",
    label: "파이브라우저",
    enLabel: "Pi Browser",
    icon: "🧭",
  },
  {
    id: "kyc",
    name: "KYC 인증",
    enName: "KYC",
    label: "KYC 인증",
    enLabel: "KYC",
    icon: "🪪",
  },
  {
    id: "developer",
    name: "개발자/SDK",
    enName: "Developer",
    label: "개발자/SDK",
    enLabel: "Developer",
    icon: "🛠️",
  },
  {
    id: "ecosystem",
    name: "생태계 App",
    enName: "Ecosystem",
    label: "생태계 App",
    enLabel: "Ecosystem",
    icon: "🌱",
  },
  {
    id: "listing",
    name: "상장/거래소",
    enName: "Exchange",
    label: "상장/거래소",
    enLabel: "Exchange",
    icon: "📈",
  },
  {
    id: "price",
    name: "시세/가치",
    enName: "Price/GCV",
    label: "시세/가치",
    enLabel: "Price/GCV",
    icon: "💎",
  },
  {
    id: "security",
    name: "보안/스팸",
    enName: "Security",
    label: "보안/스팸",
    enLabel: "Security",
    icon: "🛡️",
  },
  {
    id: "calendar",
    name: "일정/캘린더",
    enName: "Calendar",
    label: "일정/캘린더",
    enLabel: "Calendar",
    icon: "📅",
  },
  {
    id: "roadmap",
    name: "로드맵",
    enName: "Roadmap",
    label: "로드맵",
    enLabel: "Roadmap",
    icon: "🗺️️",
  },
  {
    id: "whitepaper",
    name: "백서",
    enName: "Whitepaper",
    label: "백서",
    enLabel: "Whitepaper",
    icon: "📄",
  },
  {
    id: "legal",
    name: "법률/규제",
    enName: "Legal/Reg",
    label: "법률/규제",
    enLabel: "Legal/Reg",
    icon: "⚖️",
  },
  {
    id: "global-market",
    name: "글로벌 동향",
    enName: "Global Market",
    label: "글로벌 동향",
    enLabel: "Global Market",
    icon: "🌍",
  },
  {
    id: "defi",
    name: "DeFi / 금융",
    enName: "DeFi & Finance",
    label: "DeFi / 금융",
    enLabel: "DeFi & Finance",
    icon: "🏦",
  },
  {
    id: "nft",
    name: "NFT / 메타버스",
    enName: "NFT & Metaverse",
    label: "NFT / 메타버스",
    enLabel: "NFT & Metaverse",
    icon: "🖼️",
  },
  {
    id: "tech",
    name: "AI & 블록체인 기술",
    enName: "Tech & AI",
    label: "AI & 블록체인 기술",
    enLabel: "Tech & AI",
    icon: "🤖",
  }
];

export default NEWS_CATEGORIES;

